import logging
import json

logging.basicConfig(level=logging.WARNING,
    format='%(asctime)s - %(name)s.%(levelname)-8s %(message)s')
logger = logging.getLogger(__name__)

from eds_pie.eds_pie import CIP_EDS, __version__

with open('demo.eds', 'rb') as srcfile:
    eds_content = srcfile.read()

eds = CIP_EDS(eds_content)
print("EDS Protocol: {}".format(eds.protocol or "Generic"))

eds.list()
print(eds)

eds.hcomment = """EtherNet/IP Electronic Data Sheet Generated by EDS pie v{}
                 ****************************************************************************

                 ATTENTION:

                 Changes in this file can cause configuration or communication problems.

                 ****************************************************************************""".format(__version__)

eds.fcomment = """****************************************************************************
                  EOF
                 ****************************************************************************"""

eds.save("my_demo.eds", overwrite=True)
# Converting EDS to JSON format
print(json.dumps(eds.to_json(),indent=4))

