import logging

logging.basicConfig(level=logging.WARNING,
    format='%(asctime)s - %(name)s.%(levelname)-8s %(message)s')
logger = logging.getLogger(__name__)

from eds_pie.eds_pie import CIP_EDS, __version__

with open('demo.eds', 'rb') as srcfile:
    eds_content = srcfile.read()
print(__version__)
eds = CIP_EDS(eds_content)

eds.list()
print(eds)

eds.hcomment = """EtherNet/IP Electronic Data Sheet Generated by EDS pie V2
                 ****************************************************************************

                 ATTENTION:

                 Changes in this file can cause configuration or communication problems.

                 ****************************************************************************"""

eds.fcomment = """****************************************************************************
                  EOF
                 ****************************************************************************"""

eds.save("my_demo.eds", overwrite=True)

